{{- if .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: siof
  namespace: {{ .Values.namespace }}
spec:
  groups:
    - name: siof.rules
      rules:
        - alert: SiofHighErrorRate
          expr: rate(errors_total[5m]) > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High error rate detected
{{- end }}
