deployment:
  replicas: 1
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
image:
  tag: dev
hpa:
  minReplicas: 1
  maxReplicas: 3
ingress:
  hostname: siof-dev.example.com
istio:
  enabled: false
