deployment:
  replicas: 2
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
image:
  tag: staging
hpa:
  minReplicas: 2
  maxReplicas: 6
ingress:
  hostname: siof-staging.example.com
istio:
  enabled: true
