apiVersion: v1
kind: ConfigMap
metadata:
  name: siof-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: {{ .Values.image.tag | quote }}
  STORAGE_BACKEND: {{ .Values.storage.backend | quote }}
  LOG_LEVEL: "INFO"
