apiVersion: v1
kind: Service
metadata:
  name: siof-app
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: siof-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
